In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns


In [2]:
df=pd.read_csv("G:\Sanjay_Data_Science\Data _Science_Assignment\endtoend-ml-projects-master\endtoend-ml-projects-master\hr_employee_churn_data.csv")

In [3]:
df.head()

empid  satisfaction_level  last_evaluation  number_project  \
0      1                0.38             0.53               2   
1      2                0.80             0.86               5   
2      3                0.11             0.88               7   
3      4                0.72             0.87               5   
4      5                0.37             0.52               2   

   average_montly_hours  time_spend_company  Work_accident  \
0                   157                   3              0   
1                   262                   6              0   
2                   272                   4              0   
3                   223                   5              0   
4                   159                   3              0   

   promotion_last_5years  salary  left  
0                      0     low     1  
1                      0  medium     1  
2                      0  medium     1  
3                      0     low     1  
4                      0     low     1

In [4]:
df.shape

(14999, 10)

In [5]:
X=df.drop(["empid"],axis=1)

In [6]:
X.head()

satisfaction_level  last_evaluation  number_project  average_montly_hours  \
0                0.38             0.53               2                   157   
1                0.80             0.86               5                   262   
2                0.11             0.88               7                   272   
3                0.72             0.87               5                   223   
4                0.37             0.52               2                   159   

   time_spend_company  Work_accident  promotion_last_5years  salary  left  
0                   3              0                      0     low     1  
1                   6              0                      0  medium     1  
2                   4              0                      0  medium     1  
3                   5              0                      0     low     1  
4                   3              0                      0     low     1

In [7]:
X.shape

(14999, 9)

In [8]:
y=df["left"]

In [9]:
y.head()

0    1
1    1
2    1
3    1
4    1
Name: left, dtype: int64

In [10]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14999 entries, 0 to 14998
Data columns (total 9 columns):
satisfaction_level       14997 non-null float64
last_evaluation          14999 non-null float64
number_project           14999 non-null int64
average_montly_hours     14999 non-null int64
time_spend_company       14999 non-null int64
Work_accident            14999 non-null int64
promotion_last_5years    14999 non-null int64
salary                   14999 non-null object
left                     14999 non-null int64
dtypes: float64(2), int64(6), object(1)
memory usage: 1.0+ MB


In [11]:
X.describe()

satisfaction_level  last_evaluation  number_project  \
count        14997.000000     14999.000000    14999.000000   
mean             0.612863         0.716102        3.803054   
std              0.248634         0.171169        1.232592   
min              0.090000         0.360000        2.000000   
25%              0.440000         0.560000        3.000000   
50%              0.640000         0.720000        4.000000   
75%              0.820000         0.870000        5.000000   
max              1.000000         1.000000        7.000000   

       average_montly_hours  time_spend_company  Work_accident  \
count          14999.000000        14999.000000   14999.000000   
mean             201.050337            3.498233       0.144610   
std               49.943099            1.460136       0.351719   
min               96.000000            2.000000       0.000000   
25%              156.000000            3.000000       0.000000   
50%              200.000000            3.000000       0.000000   
75%              245.000000            4.000000       0.000000   
max              310.000000           10.000000       1.000000   

       promotion_last_5years          left  
count           14999.000000  14999.000000  
mean                0.021268      0.238083  
std                 0.144281      0.425924  
min                 0.000000      0.000000  
25%                 0.000000      0.000000  
50%                 0.000000      0.000000  
75%                 0.000000      0.000000  
max                 1.000000      1.000000

In [12]:
X["satisfaction_level"].fillna(X["satisfaction_level"].mean(),inplace=True)

In [13]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14999 entries, 0 to 14998
Data columns (total 9 columns):
satisfaction_level       14999 non-null float64
last_evaluation          14999 non-null float64
number_project           14999 non-null int64
average_montly_hours     14999 non-null int64
time_spend_company       14999 non-null int64
Work_accident            14999 non-null int64
promotion_last_5years    14999 non-null int64
salary                   14999 non-null object
left                     14999 non-null int64
dtypes: float64(2), int64(6), object(1)
memory usage: 1.0+ MB


In [14]:
X.head()

satisfaction_level  last_evaluation  number_project  average_montly_hours  \
0                0.38             0.53               2                   157   
1                0.80             0.86               5                   262   
2                0.11             0.88               7                   272   
3                0.72             0.87               5                   223   
4                0.37             0.52               2                   159   

   time_spend_company  Work_accident  promotion_last_5years  salary  left  
0                   3              0                      0     low     1  
1                   6              0                      0  medium     1  
2                   4              0                      0  medium     1  
3                   5              0                      0     low     1  
4                   3              0                      0     low     1

In [15]:
X["salary"].unique()

array(['low', 'medium', 'high'], dtype=object)

In [16]:
X=pd.get_dummies(X,columns=["salary"],drop_first=True)

In [17]:
X.head()

satisfaction_level  last_evaluation  number_project  average_montly_hours  \
0                0.38             0.53               2                   157   
1                0.80             0.86               5                   262   
2                0.11             0.88               7                   272   
3                0.72             0.87               5                   223   
4                0.37             0.52               2                   159   

   time_spend_company  Work_accident  promotion_last_5years  left  salary_low  \
0                   3              0                      0     1           1   
1                   6              0                      0     1           0   
2                   4              0                      0     1           0   
3                   5              0                      0     1           1   
4                   3              0                      0     1           1   

   salary_medium  
0              0  
1              1  
2              1  
3              0  
4              0

In [18]:
X.shape

(14999, 10)

In [19]:
X=X.drop(["left"],axis=1)

In [20]:
X.head()

satisfaction_level  last_evaluation  number_project  average_montly_hours  \
0                0.38             0.53               2                   157   
1                0.80             0.86               5                   262   
2                0.11             0.88               7                   272   
3                0.72             0.87               5                   223   
4                0.37             0.52               2                   159   

   time_spend_company  Work_accident  promotion_last_5years  salary_low  \
0                   3              0                      0           1   
1                   6              0                      0           0   
2                   4              0                      0           0   
3                   5              0                      0           1   
4                   3              0                      0           1   

   salary_medium  
0              0  
1              1  
2              1  
3              0  
4              0

In [21]:
X.shape

(14999, 9)

In [22]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=42,stratify=y)

In [23]:
y.drop_duplicates()

0       1
2000    0
Name: left, dtype: int64

In [24]:
from sklearn.ensemble import RandomForestClassifier


In [25]:
Random=RandomForestClassifier()

In [26]:
Random.fit(X_train,y_train)

G:\Sanjay_Data_Science\Data_Science_Software\Anaconda\run2\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [27]:
Random.predict(X_test[0:1])

array([0], dtype=int64)

In [28]:
X_test.head()

satisfaction_level  last_evaluation  number_project  \
3946                 0.52             0.92               4   
10652                0.19             0.63               4   
5330                 0.59             0.51               3   
2669                 0.33             0.70               5   
10164                0.52             0.80               3   

       average_montly_hours  time_spend_company  Work_accident  \
3946                    150                   2              1   
10652                   278                   6              0   
5330                    203                   2              1   
2669                    271                   4              0   
10164                   156                   3              0   

       promotion_last_5years  salary_low  salary_medium  
3946                       0           1              0  
10652                      0           1              0  
5330                       0           0              1  
2669                       0           1              0  
10164                      0           0              1

In [29]:
X_test[:1]

satisfaction_level  last_evaluation  number_project  \
3946                0.52             0.92               4   

      average_montly_hours  time_spend_company  Work_accident  \
3946                   150                   2              1   

      promotion_last_5years  salary_low  salary_medium  
3946                      0           1              0

In [30]:
Random.predict(X_test[:1])

array([0], dtype=int64)

In [31]:
Random.score(X_test,y_test)

0.9877777777777778

In [32]:
Random.predict(X_test)

array([0, 0, 0, ..., 0, 1, 0], dtype=int64)

In [33]:
Random.predict([[0.42,0.82,3,140,3,0,1,0,0]])

array([0], dtype=int64)